authors:
  vedranmiletic:
    name: Vedran Miletić
    description: Principal investigator
    avatar: https://github.com/vedranmiletic.png
  mateaturalija:
    name: Matea Turalija
    description: PhD student
    avatar: https://github.com/mateaturalija.png
